apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyZWRvb3NvbHV0aW9ucyIsInBhc3N3b3JkIjoiU3BAbnRyMzMjQCEiLCJlbWFpbCI6IndlYm1hc3RlckByZWRvby5zb2x1dGlvbnMiLCJhdXRoIjoiY21Wa2IyOXpiMngxZEdsdmJuTTZVM0JBYm5SeU16TWpRQ0U9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2021-08-12T22:56:42Z"
  name: regcred
  namespace: rcloud
  resourceVersion: "8840675"
  uid: e2efc03d-8840-4691-b74e-767538c69cda
type: kubernetes.io/dockerconfigjson
