apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onepage-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - onepage.spantreeng.com
      secretName: default-server-secret
  rules:
  - host: onepage.spantreeng.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: onepage
            port: 
              number: 80
