apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepage
  namespace: onepage
  labels:
    app: onepage
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: onepage
  template:
    metadata:
      labels:
        app: onepage
        tier: frontend
    spec:
      containers:
        - image: redoosolutions/pythonscripts:one-1.1.8-rc
          name: onepage
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: onecred
