apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spansecret
  namespace: onepage
spec:
  encryptedData:
    password: AgBgMGbpOe7rd+pzf0E7xlV17thlaGohXnE+RHihFOJBA6YsbUe9NTR2lX995TYqr0u9vvFpBmOxqNWsE9cMIJnsu2Y2f6eePEuRIQnVK+4J0t+wkYhN+XE0H5zhvpM6qbiDWlk1ZY1EsvQcKxwMG8Wd2uEacRArp7jAHelkn/g4u6AIDImH5dfdQfR1eH44nqdT2q9Y4gSmfLUTqit2siK1w7n3biZDXteYBQ9hFJzW3ITtdC/Id5fBx1t0b8jZeq7MaxdTSjHhYlsLKh5TzpAKIZ69S56mKp+A69wTRK3y2zOQsKgQYgJvSjL00mjF+k0cdo3vOqSsSGoWgc4sgrrqSzx+VE8Ct3JCRXAFZDg1tx6KJY3ybpRcO4bAS+ODILrzlNP+hfgtT87f6QeyA7R1rxN/yjsu85NmLTgMIdrqWSE60K2Sm3JPbE0G7QoZWEyhAK9qBxR4HicPtw12ywQEl/CX6FhkUKwPE8uvsRgm3FuE/uGsZAYxOgz9CKR5PfXslRyFte+wfJ1n4myf8idBEMElQx8LH1PcQcKSq612edS3CaAkT+YEWM9NvkTpKEs8CfTtgVmm1PQlp2tQBMzukz+WZUhHUSprSjv1LMvtUMyWVkydVruWyy9o8cNHY8QOooy880LVIuvR+wQjrkIGzTNQ6VcYZvqaYeMnxqUY+cJE9eAUlkAWYxpMk0hXUB+RIxfYHAb/Ag==
    username: AgBUKXIZEh177cBHd2s2yz04k1SOGa0Zn9/tolCNpCyxehxzi/icPOJXCiL6boSHCn+GNulBKDJXzkLXonD4qpmn7+L0SJodSxj59fDYQXXo78sk13BmT1bu5GUeBnhIqii7+NQ/43T/Z5JCSaHJvtlQpX3D05OYT6AZoFNmcLkTX6Csq0eOBH7SRGq6ghkI5kndfLkAGP4M3dn9JB3CJJ1k1DoKwUGjqPafXVlPkC1H65wfJ3oadApCUH6Q2JRJFPW+bAkaKD7aHQb+Ie96fLM7mP7LCMMcOqVIJD2qBGuxbFK6Y1C1lgnUfrsSqC1WBSsF91+noqRSFQNijW7SFPaMcz25kM3GCXoz5WZ9hzrV4m0yKoAmB3hp/vqnaU7xR9uDrUn8d/c1WdockuxRGJjxOTQDvEz2vUQCnzUH/zJ3xU4EVjsVnKOI+2JfBzKa2RXisjFUFDB5sZBu7fMOCZm5DBjY3qN99fImqHKsDxeDDQ1Efqel2EIy/u+nPMVwbC3yuENDpcHBf8WyOlAYmj0p68YzlTnKpUTh2Mmptg/lOF4lpd+KsNg38tgp6WKIkz4JzC1ErrYbBqZDLty9niJGyP20Z4y2EHLBz7D/qvfzn/PQfVnLf1fuaj/pEh2l+qdSC5MbiGANYVA4CNXLy6fvg2JPRbev6DB84xD2l5TvVClvZ7xjWQ/LyeIBFFGiBbHLQd2jGQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: spansecret
      namespace: onepage
    type: Opaque

