FROM httpd

## Update odoo configuration file 
# COPY /Users/inigodwin/PycharmProjects/devopsdemo/index.html /htdocs
COPY config htdocs
# Update custom addons folder
# COPY extra-addons /mnt/extra-addons 

#RUN chown -R odoo:odoo /mnt/extra-addons
